'''
Define structs
'''
from ctypes import *


class LIGHT_BANK(Structure):
    _fields_ = [
        ('degRotX_0', c_int16),
        ('degRotY_0', c_int16),
        ('colR_0', c_int16),
        ('colG_0', c_int16),
        ('colB_0', c_int16),
        ('colA_0', c_int16),
        ('degRotX_1', c_int16),
        ('degRotY_1', c_int16),
        ('colR_1', c_int16),
        ('colG_1', c_int16),
        ('colB_1', c_int16),
        ('colA_1', c_int16),
        ('degRotX_2', c_int16),
        ('degRotY_2', c_int16),
        ('colR_2', c_int16),
        ('colG_2', c_int16),
        ('colB_2', c_int16),
        ('colA_2', c_int16),
        ('colR_u', c_int16),
        ('colG_u', c_int16),
        ('colB_u', c_int16),
        ('colA_u', c_int16),
        ('colR_d', c_int16),
        ('colG_d', c_int16),
        ('colB_d', c_int16),
        ('colA_d', c_int16),
        ('degRotX_s', c_int16),
        ('degRotY_s', c_int16),
        ('colR_s', c_int16),
        ('colG_s', c_int16),
        ('colB_s', c_int16),
        ('colA_s', c_int16),
        ('envDif_colR', c_int16),
        ('envDif_colG', c_int16),
        ('envDif_colB', c_int16),
        ('envDif_colA', c_int16),
        ('envSpc_colR', c_int16),
        ('envSpc_colG', c_int16),
        ('envSpc_colB', c_int16),
        ('envSpc_colA', c_int16),
        ('envDif', c_int16),
        ('envSpc_0', c_int16),
        ('envSpc_1', c_int16),
        ('envSpc_2', c_int16),
        ('envSpc_3', c_int16),
        ('pad', c_uint8 * 2),
    ]


class LIGHT_SCATTERING_BANK(Structure):
    _fields_ = [
        ('sunRotX', c_int16),
        ('sunRotY', c_int16),
        ('distanceMul', c_int16),
        ('sunR', c_int16),
        ('sunG', c_int16),
        ('sunB', c_int16),
        ('sunA', c_int16),
        ('pad_0', c_uint8 * 2),
        ('lsHGg', c_float),
        ('lsBetaRay', c_float),
        ('lsBetaMie', c_float),
        ('blendCoef', c_int16),
        ('reflectanceR', c_int16),
        ('reflectanceG', c_int16),
        ('reflectanceB', c_int16),
        ('reflectanceA', c_int16),
        ('pad_1', c_uint8 * 2),
    ]


class LENS_FLARE_BANK(Structure):
    _fields_ = [
        ('texId', c_int8),
        ('isFlare', c_uint8),
        ('enableRoll', c_uint8),
        ('enableScale', c_uint8),
        ('locateDistRate', c_float),
        ('texScale', c_float),
        ('colR', c_int16),
        ('colG', c_int16),
        ('colB', c_int16),
        ('colA', c_int16),
    ]


class DOF_BANK(Structure):
    _fields_ = [
        ('farDofBegin', c_float),
        ('farDofEnd', c_float),
        ('farDofMul', c_uint8),
        ('pad_0', c_uint8 * 3),
        ('nearDofBegin', c_float),
        ('nearDofEnd', c_float),
        ('nearDofMul', c_uint8),
        ('pad_1', c_uint8 * 3),
        ('dispersionSq', c_float),
    ]


class TONE_MAP_BANK(Structure):
    _fields_ = [
        ('bloomBegin', c_int8),
        ('bloomMul', c_int8),
        ('bloomBeginFar', c_int8),
        ('bloomMulFar', c_int8),
        ('bloomNearDist', c_float),
        ('bloomFarDist', c_float),
        ('grayKeyValue', c_float),
        ('minAdaptedLum', c_float),
        ('maxAdapredLum', c_float),
        ('adaptSpeed', c_float),
        ('lightShaftBegin', c_int8),
        ('pad_0', c_uint8 * 3),
        ('lightShaftPower', c_float),
        ('lightShaftAttenRate', c_float),
    ]


class TONE_CORRECT_BANK(Structure):
    _fields_ = [
        ('brightnessR', c_float),
        ('brightnessG', c_float),
        ('brightnessB', c_float),
        ('contrastR', c_float),
        ('contrastG', c_float),
        ('contrastB', c_float),
        ('saturation', c_float),
        ('hue', c_float),
    ]


class SHADOW_BANK(Structure):
    _fields_ = [
        ('lightDegRotX', c_int16),
        ('lightDegRotY', c_int16),
        ('densityRatio', c_int16),
        ('colR', c_int16),
        ('colG', c_int16),
        ('colB', c_int16),
        ('beginDist', c_float),
        ('endDist', c_float),
        ('calibulateFar', c_float),
        ('fadeBeginDist', c_float),
        ('fadeDist', c_float),
        ('persedDepthOffset', c_float),
        ('??radFactor', c_float),
        ('shadowVolumeDepth', c_float),
    ]


class LENS_FLARE_EX_BANK(Structure):
    _fields_ = [
        ('lightDegRotX', c_int16),
        ('lightDegRotY', c_int16),
        ('colR', c_int16),
        ('colG', c_int16),
        ('colB', c_int16),
        ('colA', c_int16),
        ('lightDist', c_float),
    ]


class ENV_LIGHT_TEX_BANK(Structure):
    _fields_ = [
        ('isUse', c_int8),
        ('autoUpdate', c_int8),
        ('pad_0', c_uint8 * 12),
        ('invMulCol', c_int16),
        ('resNameId_Dif0', c_int16),
        ('invMulCol_Dif0', c_int16),
        ('sepcPow_Dif0', c_float),
        ('pad_Dif0', c_uint8 * 8),
        ('resNameId_Spc0', c_int16),
        ('invMulCol_Spc0', c_int16),
        ('sepcPow_Spc0', c_float),
        ('pad_Spc0', c_uint8 * 8),
        ('resNameId_Spc1', c_int16),
        ('invMulCol_Spc1', c_int16),
        ('sepcPow_Spc1', c_float),
        ('pad_Spc1', c_uint8 * 8),
        ('resNameId_Spc2', c_int16),
        ('invMulCol_Spc2', c_int16),
        ('sepcPow_Spc2', c_float),
        ('pad_Spc2', c_uint8 * 8),
        ('resNameId_Spc3', c_int16),
        ('invMulCol_Spc3', c_int16),
        ('sepcPow_Spc3', c_float),
        ('pad_Spc3', c_uint8 * 8),
        ('degRotX_00', c_int16),
        ('degRotY_00', c_int16),
        ('colR_00', c_int16),
        ('colG_00', c_int16),
        ('colB_00', c_int16),
        ('colA_00', c_int16),
        ('pad_00', c_uint8 * 4),
        ('degRotX_01', c_int16),
        ('degRotY_01', c_int16),
        ('colR_01', c_int16),
        ('colG_01', c_int16),
        ('colB_01', c_int16),
        ('colA_01', c_int16),
        ('pad_01', c_uint8 * 4),
        ('degRotX_02', c_int16),
        ('degRotY_02', c_int16),
        ('colR_02', c_int16),
        ('colG_02', c_int16),
        ('colB_02', c_int16),
        ('colA_02', c_int16),
        ('pad_02', c_uint8 * 4),
        ('degRotX_03', c_int16),
        ('degRotY_03', c_int16),
        ('colR_03', c_int16),
        ('colG_03', c_int16),
        ('colB_03', c_int16),
        ('colA_03', c_int16),
        ('pad_03', c_uint8 * 4),
        ('degRotX_04', c_int16),
        ('degRotY_04', c_int16),
        ('colR_04', c_int16),
        ('colG_04', c_int16),
        ('colB_04', c_int16),
        ('colA_04', c_int16),
        ('pad_04', c_uint8 * 4),
        ('degRotX_05', c_int16),
        ('degRotY_05', c_int16),
        ('colR_05', c_int16),
        ('colG_05', c_int16),
        ('colB_05', c_int16),
        ('colA_05', c_int16),
        ('pad_05', c_uint8 * 4),
        ('degRotX_06', c_int16),
        ('degRotY_06', c_int16),
        ('colR_06', c_int16),
        ('colG_06', c_int16),
        ('colB_06', c_int16),
        ('colA_06', c_int16),
        ('pad_06', c_uint8 * 4),
        ('degRotX_07', c_int16),
        ('degRotY_07', c_int16),
        ('colR_07', c_int16),
        ('colG_07', c_int16),
        ('colB_07', c_int16),
        ('colA_07', c_int16),
        ('pad_07', c_uint8 * 4),
        ('degRotX_08', c_int16),
        ('degRotY_08', c_int16),
        ('colR_08', c_int16),
        ('colG_08', c_int16),
        ('colB_08', c_int16),
        ('colA_08', c_int16),
        ('pad_08', c_uint8 * 4),
        ('degRotX_09', c_int16),
        ('degRotY_09', c_int16),
        ('colR_09', c_int16),
        ('colG_09', c_int16),
        ('colB_09', c_int16),
        ('colA_09', c_int16),
        ('pad_09', c_uint8 * 4),
    ]


class LOD_BANK(Structure):
    _fields_ = [
        ('lv01_BorderDist', c_float),
        ('lv01_PlayDist', c_float),
        ('lv12_BorderDist', c_float),
        ('lv12_PlayDist', c_float),
    ]


class EQUIP_PARAM_WEAPON_ST(Structure):
    _fields_ = [
        ('behaviorVariationId', c_int32),
        ('sortId', c_int32),
        ('wanderingEquipId', c_uint32),
        ('weight', c_float),
        ('weaponWeightRate', c_float),
        ('fixPrice', c_int32),
        ('basicPrice', c_int32),
        ('sellValue', c_int32),
        ('correctStrength', c_float),
        ('correctAgility', c_float),
        ('correctMagic', c_float),
        ('correctFaith', c_float),
        ('physGuardCutRate', c_float),
        ('magGuardCutRate', c_float),
        ('fireGuardCutRate', c_float),
        ('thunGuardCutRate', c_float),
        ('spEffectBehaviorId0', c_int32),
        ('spEffectBehaviorId1', c_int32),
        ('spEffectBehaviorId2', c_int32),
        ('residentSpEffectId', c_int32),
        ('residentSpEffectId1', c_int32),
        ('residentSpEffectId2', c_int32),
        ('materialSetId', c_int32),
        ('originEquipWep', c_int32),
        ('originEquipWep1', c_int32),
        ('originEquipWep2', c_int32),
        ('originEquipWep3', c_int32),
        ('originEquipWep4', c_int32),
        ('originEquipWep5', c_int32),
        ('originEquipWep6', c_int32),
        ('originEquipWep7', c_int32),
        ('originEquipWep8', c_int32),
        ('originEquipWep9', c_int32),
        ('originEquipWep10', c_int32),
        ('originEquipWep11', c_int32),
        ('originEquipWep12', c_int32),
        ('originEquipWep13', c_int32),
        ('originEquipWep14', c_int32),
        ('originEquipWep15', c_int32),
        ('antiDemonDamageRate', c_float),
        ('antSaintDamageRate', c_float),
        ('antWeakA_DamageRate', c_float),
        ('antWeakB_DamageRate', c_float),
        ('vagrantItemLotId', c_int32),
        ('vagrantBonusEneDropItemLotId', c_int32),
        ('vagrantItemEneDropItemLotId', c_int32),
        ('equipModelId', c_uint16),
        ('iconId', c_uint16),
        ('durability', c_uint16),
        ('durabilityMax', c_uint16),
        ('attackThrowEscape', c_uint16),
        ('parryDamageLife', c_int16),
        ('attackBasePhysics', c_uint16),
        ('attackBaseMagic', c_uint16),
        ('attackBaseFire', c_uint16),
        ('attackBaseThunder', c_uint16),
        ('attackBaseStamina', c_uint16),
        ('saWeaponDamage', c_uint16),
        ('saDurability', c_int16),
        ('guardAngle', c_int16),
        ('staminaGuardDef', c_int16),
        ('reinforceTypeId', c_int16),
        ('trophySGradeId', c_int16),
        ('trophySeqId', c_int16),
        ('throwAtkRate', c_int16),
        ('bowDistRate', c_int16),
        ('equipModelCategory', c_uint8),
        ('equipModelGender', c_uint8),
        ('weaponCategory', c_uint8),
        ('wepmotionCategory', c_uint8),
        ('guardmotionCategory', c_uint8),
        ('atkMaterial', c_uint8),
        ('defMaterial', c_uint8),
        ('defSfxMaterial', c_uint8),
        ('correctType', c_uint8),
        ('spAttribute', c_uint8),
        ('spAtkcategory', c_uint8),
        ('wepmotionOneHandId', c_uint8),
        ('wepmotionBothHandId', c_uint8),
        ('properStrength', c_uint8),
        ('properAgility', c_uint8),
        ('properMagic', c_uint8),
        ('properFaith', c_uint8),
        ('overStrength', c_uint8),
        ('attackBaseParry', c_uint8),
        ('defenseBaseParry', c_uint8),
        ('guardBaseRepel', c_uint8),
        ('attackBaseRepel', c_uint8),
        ('guardCutCancelRate', c_int8),
        ('guardLevel', c_int8),
        ('slashGuardCutRate', c_int8),
        ('blowGuardCutRate', c_int8),
        ('thrustGuardCutRate', c_int8),
        ('poisonGuardResist', c_int8),
        ('diseaseGuardResist', c_int8),
        ('bloodGuardResist', c_int8),
        ('curseGuardResist', c_int8),
        ('isDurabilityDivergence', c_uint8),
        ('rightHandEquipable', c_uint8, 1),
        ('leftHandEquipable', c_uint8, 1),
        ('bothHandEquipable', c_uint8, 1),
        ('arrowSlotEquipable', c_uint8, 1),
        ('boltSlotEquipable', c_uint8, 1),
        ('enableGuard', c_uint8, 1),
        ('enableParry', c_uint8, 1),
        ('enableMagic', c_uint8, 1),
        ('enableSorcery', c_uint8, 1),
        ('enableMiracle', c_uint8, 1),
        ('enableVowMagic', c_uint8, 1),
        ('isNormalAttackType', c_uint8, 1),
        ('isBlowAttackType', c_uint8, 1),
        ('isSlashAttackType', c_uint8, 1),
        ('isThrustAttackType', c_uint8, 1),
        ('isEnhance', c_uint8, 1),
        ('isLuckCorrect', c_uint8, 1),
        ('isCustom', c_uint8, 1),
        ('disableBaseChangeReset', c_uint8, 1),
        ('disableRepair', c_uint8, 1),
        ('isDarkHand', c_uint8, 1),
        ('simpleModelForDlc', c_uint8, 1),
        ('lanternWep', c_uint8, 1),
        ('isVersusGhostWep', c_uint8, 1),
        ('baseChangeCategory', c_uint8, 6),
        ('isDragonSlayer', c_uint8, 1),
        ('isDeposit', c_uint8, 1),
        ('disableMultiDropShare', c_uint8, 1),
        ('pad_0', c_uint8 * 1),
        ('oldSortId', c_int16),
        ('pad_1', c_uint8 * 8),
    ]


class EQUIP_PARAM_PROTECTOR_ST(Structure):
    _fields_ = [
        ('sortId', c_int32),
        ('wanderingEquipId', c_uint32),
        ('vagrantItemLotId', c_int32),
        ('vagrantBonusEneDropItemLotId', c_int32),
        ('vagrantItemEneDropItemLotId', c_int32),
        ('fixPrice', c_int32),
        ('basicPrice', c_int32),
        ('sellValue', c_int32),
        ('weight', c_float),
        ('residentSpEffectId', c_int32),
        ('residentSpEffectId2', c_int32),
        ('residentSpEffectId3', c_int32),
        ('materialSetId', c_int32),
        ('partsDamageRate', c_float),
        ('corectSARecover', c_float),
        ('originEquipPro', c_int32),
        ('originEquipPro1', c_int32),
        ('originEquipPro2', c_int32),
        ('originEquipPro3', c_int32),
        ('originEquipPro4', c_int32),
        ('originEquipPro5', c_int32),
        ('originEquipPro6', c_int32),
        ('originEquipPro7', c_int32),
        ('originEquipPro8', c_int32),
        ('originEquipPro9', c_int32),
        ('originEquipPro10', c_int32),
        ('originEquipPro11', c_int32),
        ('originEquipPro12', c_int32),
        ('originEquipPro13', c_int32),
        ('originEquipPro14', c_int32),
        ('originEquipPro15', c_int32),
        ('faceScaleM_ScaleX', c_float),
        ('faceScaleM_ScaleZ', c_float),
        ('faceScaleM_MaxX', c_float),
        ('faceScaleM_MaxZ', c_float),
        ('faceScaleF_ScaleX', c_float),
        ('faceScaleF_ScaleZ', c_float),
        ('faceScaleF_MaxX', c_float),
        ('faceScaleF_MaxZ', c_float),
        ('qwcId', c_int32),
        ('equipModelId', c_uint16),
        ('iconIdM', c_uint16),
        ('iconIdF', c_uint16),
        ('knockBack', c_uint16),
        ('knockbackBounceRate', c_uint16),
        ('durability', c_uint16),
        ('durabilityMax', c_uint16),
        ('saDurability', c_int16),
        ('defFlickPower', c_uint16),
        ('defensePhysics', c_uint16),
        ('defenseMagic', c_uint16),
        ('defenseFire', c_uint16),
        ('defenseThunder', c_uint16),
        ('defenseSlash', c_int16),
        ('defenseBlow', c_int16),
        ('defenseThrust', c_int16),
        ('resistPoison', c_uint16),
        ('resistDisease', c_uint16),
        ('resistBlood', c_uint16),
        ('resistCurse', c_uint16),
        ('reinforceTypeId', c_int16),
        ('trophySGradeId', c_int16),
        ('shopLv', c_int16),
        ('knockbackParamId', c_uint8),
        ('flickDamageCutRate', c_uint8),
        ('equipModelCategory', c_uint8),
        ('equipModelGender', c_uint8),
        ('protectorCategory', c_uint8),
        ('defenseMaterial', c_uint8),
        ('defenseMaterialSfx', c_uint8),
        ('partsDmgType', c_uint8),
        ('defenseMaterial_Weak', c_uint8),
        ('defenseMaterialSfx_Weak', c_uint8),
        ('isDeposit', c_uint8, 1),
        ('headEquip', c_uint8, 1),
        ('bodyEquip', c_uint8, 1),
        ('armEquip', c_uint8, 1),
        ('legEquip', c_uint8, 1),
        ('useFaceScale', c_uint8, 1),
        ('invisibleFlag00', c_uint8, 1),
        ('invisibleFlag01', c_uint8, 1),
        ('invisibleFlag02', c_uint8, 1),
        ('invisibleFlag03', c_uint8, 1),
        ('invisibleFlag04', c_uint8, 1),
        ('invisibleFlag05', c_uint8, 1),
        ('invisibleFlag06', c_uint8, 1),
        ('invisibleFlag07', c_uint8, 1),
        ('invisibleFlag08', c_uint8, 1),
        ('invisibleFlag09', c_uint8, 1),
        ('invisibleFlag10', c_uint8, 1),
        ('invisibleFlag11', c_uint8, 1),
        ('invisibleFlag12', c_uint8, 1),
        ('invisibleFlag13', c_uint8, 1),
        ('invisibleFlag14', c_uint8, 1),
        ('invisibleFlag15', c_uint8, 1),
        ('invisibleFlag16', c_uint8, 1),
        ('invisibleFlag17', c_uint8, 1),
        ('invisibleFlag18', c_uint8, 1),
        ('invisibleFlag19', c_uint8, 1),
        ('invisibleFlag20', c_uint8, 1),
        ('invisibleFlag21', c_uint8, 1),
        ('invisibleFlag22', c_uint8, 1),
        ('invisibleFlag23', c_uint8, 1),
        ('invisibleFlag24', c_uint8, 1),
        ('invisibleFlag25', c_uint8, 1),
        ('invisibleFlag26', c_uint8, 1),
        ('invisibleFlag27', c_uint8, 1),
        ('invisibleFlag28', c_uint8, 1),
        ('invisibleFlag29', c_uint8, 1),
        ('invisibleFlag30', c_uint8, 1),
        ('invisibleFlag31', c_uint8, 1),
        ('invisibleFlag32', c_uint8, 1),
        ('invisibleFlag33', c_uint8, 1),
        ('invisibleFlag34', c_uint8, 1),
        ('invisibleFlag35', c_uint8, 1),
        ('invisibleFlag36', c_uint8, 1),
        ('invisibleFlag37', c_uint8, 1),
        ('invisibleFlag38', c_uint8, 1),
        ('invisibleFlag39', c_uint8, 1),
        ('invisibleFlag40', c_uint8, 1),
        ('invisibleFlag41', c_uint8, 1),
        ('invisibleFlag42', c_uint8, 1),
        ('invisibleFlag43', c_uint8, 1),
        ('invisibleFlag44', c_uint8, 1),
        ('invisibleFlag45', c_uint8, 1),
        ('invisibleFlag46', c_uint8, 1),
        ('invisibleFlag47', c_uint8, 1),
        ('disableMultiDropShare', c_uint8, 1),
        ('simpleModelForDlc', c_uint8, 1),
        ('pad_0', c_uint8 * 1),
        ('oldSortId', c_int16),
        ('pad_1', c_uint8 * 6),
    ]


class EQUIP_PARAM_ACCESSORY_ST(Structure):
    _fields_ = [
        ('refId', c_int32),
        ('sfxVariationId', c_int32),
        ('weight', c_float),
        ('behaviorId', c_int32),
        ('basicPrice', c_int32),
        ('sellValue', c_int32),
        ('sortId', c_int32),
        ('qwcId', c_int32),
        ('equipModelId', c_uint16),
        ('iconId', c_uint16),
        ('shopLv', c_int16),
        ('trophySGradeId', c_int16),
        ('trophySeqId', c_int16),
        ('equipModelCategory', c_uint8),
        ('equipModelGender', c_uint8),
        ('accessoryCategory', c_uint8),
        ('refCategory', c_uint8),
        ('spEffectCategory', c_uint8),
        ('pad', c_uint8 * 1),
        ('vagrantItemLotId', c_int32),
        ('vagrantBonusEneDropItemLotId', c_int32),
        ('vagrantItemEneDropItemLotId', c_int32),
        ('isDeposit', c_uint8, 1),
        ('isEquipOutBrake', c_uint8, 1),
        ('disableMultiDropShare', c_uint8, 1),
        ('pad1', c_uint8 * 3),
    ]


class EQUIP_PARAM_GOODS_ST(Structure):
    _fields_ = [
        ('refId', c_int32),
        ('sfxVariationId', c_int32),
        ('weight', c_float),
        ('basicPrice', c_int32),
        ('sellValue', c_int32),
        ('behaviorId', c_int32),
        ('replaceItemId', c_int32),
        ('sortId', c_int32),
        ('qwcId', c_int32),
        ('yesNoDialogMessageId', c_int32),
        ('magicId', c_int32),
        ('iconId', c_uint16),
        ('modelId', c_uint16),
        ('shopLv', c_int16),
        ('compTrophySedId', c_int16),
        ('trophySeqId', c_int16),
        ('maxNum', c_int16),
        ('consumeHeroPoint', c_uint8),
        ('overDexterity', c_uint8),
        ('goodsType', c_uint8),
        ('refCategory', c_uint8),
        ('spEffectCategory', c_uint8),
        ('goodsCategory', c_uint8),
        ('goodsUseAnim', c_uint8),
        ('opmeMenuType', c_uint8),
        ('useLimitCategory', c_uint8),
        ('replaceCategory', c_uint8),
        ('vowType0', c_uint8, 1),
        ('vowType1', c_uint8, 1),
        ('vowType2', c_uint8, 1),
        ('vowType3', c_uint8, 1),
        ('vowType4', c_uint8, 1),
        ('vowType5', c_uint8, 1),
        ('vowType6', c_uint8, 1),
        ('vowType7', c_uint8, 1),
        ('vowType8', c_uint8, 1),
        ('vowType9', c_uint8, 1),
        ('vowType10', c_uint8, 1),
        ('vowType11', c_uint8, 1),
        ('vowType12', c_uint8, 1),
        ('vowType13', c_uint8, 1),
        ('vowType14', c_uint8, 1),
        ('vowType15', c_uint8, 1),
        ('enable_live', c_uint8, 1),
        ('enable_gray', c_uint8, 1),
        ('enable_white', c_uint8, 1),
        ('enable_black', c_uint8, 1),
        ('enable_multi', c_uint8, 1),
        ('disable_offline', c_uint8, 1),
        ('isEquip', c_uint8, 1),
        ('isConsume', c_uint8, 1),
        ('isAutoEquip', c_uint8, 1),
        ('isEstablishment', c_uint8, 1),
        ('isOnlyOne', c_uint8, 1),
        ('isDrop', c_uint8, 1),
        ('isDeposit', c_uint8, 1),
        ('isDisableHand', c_uint8, 1),
        ('IsTravelItem', c_uint8, 1),
        ('isSuppleItem', c_uint8, 1),
        ('isFullSuppleItem', c_uint8, 1),
        ('isEnhance', c_uint8, 1),
        ('isFixItem', c_uint8, 1),
        ('disableMultiDropShare', c_uint8, 1),
        ('disableUseAtColiseum', c_uint8, 1),
        ('disableUseAtOutOfColiseum', c_uint8, 1),
        ('pad', c_uint8 * 9),
        ('vagrantItemLotId', c_int32),
        ('vagrantBonusEneDropItemLotId', c_int32),
        ('vagrantItemEneDropItemLotId', c_int32),
    ]


class REINFORCE_PARAM_WEAPON_ST(Structure):
    _fields_ = [
        ('physicsAtkRate', c_float),
        ('magicAtkRate', c_float),
        ('fireAtkRate', c_float),
        ('thunderAtkRate', c_float),
        ('staminaAtkRate', c_float),
        ('saWeaponAtkRate', c_float),
        ('saDurabilityRate', c_float),
        ('correctStrengthRate', c_float),
        ('correctAgilityRate', c_float),
        ('correctMagicRate', c_float),
        ('correctFaithRate', c_float),
        ('physicsGuardCutRate', c_float),
        ('magicGuardCutRate', c_float),
        ('fireGuardCutRate', c_float),
        ('thunderGuardCutRate', c_float),
        ('poisonGuardResistRate', c_float),
        ('diseaseGuardResistRate', c_float),
        ('bloodGuardResistRate', c_float),
        ('curseGuardResistRate', c_float),
        ('staminaGuardDefRate', c_float),
        ('spEffectId1', c_uint8),
        ('spEffectId2', c_uint8),
        ('spEffectId3', c_uint8),
        ('residentSpEffectId1', c_uint8),
        ('residentSpEffectId2', c_uint8),
        ('residentSpEffectId3', c_uint8),
        ('materialSetId', c_uint8),
        ('pad', c_uint8 * 9),
    ]


class REINFORCE_PARAM_PROTECTOR_ST(Structure):
    _fields_ = [
        ('physicsDefRate', c_float),
        ('magicDefRate', c_float),
        ('fireDefRate', c_float),
        ('thunderDefRate', c_float),
        ('slashDefRate', c_float),
        ('blowDefRate', c_float),
        ('thrustDefRate', c_float),
        ('resistPoisonRate', c_float),
        ('resistDiseaseRate', c_float),
        ('resistBloodRate', c_float),
        ('resistCurseRate', c_float),
        ('residentSpEffectId1', c_uint8),
        ('residentSpEffectId2', c_uint8),
        ('residentSpEffectId3', c_uint8),
        ('materialSetId', c_uint8),
    ]


class EQUIP_MTRL_SET_PARAM_ST(Structure):
    _fields_ = [
        ('materialId01', c_int32),
        ('materialId02', c_int32),
        ('materialId03', c_int32),
        ('materialId04', c_int32),
        ('materialId05', c_int32),
        ('itemNum01', c_int8),
        ('itemNum02', c_int8),
        ('itemNum03', c_int8),
        ('itemNum04', c_int8),
        ('itemNum05', c_int8),
        ('isDisableDispNum01', c_uint8, 1),
        ('isDisableDispNum02', c_uint8, 1),
        ('isDisableDispNum03', c_uint8, 1),
        ('isDisableDispNum04', c_uint8, 1),
        ('isDisableDispNum05', c_uint8, 1),
        ('pad', c_uint8 * 6),
    ]


class SHOP_LINEUP_PARAM(Structure):
    _fields_ = [
        ('equipId', c_int32),
        ('value', c_int32),
        ('mtrlId', c_int32),
        ('eventFlag', c_int32),
        ('qwcId', c_int32),
        ('sellQuantity', c_int16),
        ('shopType', c_uint8),
        ('equipType', c_uint8),
        ('pad_0', c_uint8 * 8),
    ]


class AI_STANDARD_INFO_BANK(Structure):
    _fields_ = [
        ('RadarRange', c_uint16),
        ('RadarAngleX', c_uint8),
        ('RadarAngleY', c_uint8),
        ('TerritorySize', c_uint16),
        ('ThreatBeforeAttackRate', c_uint8),
        ('ForceThreatOnFirstLocked', c_uint8),
        ('reserve0', c_uint8 * 24),
        ('Attack1_Distance', c_uint16),
        ('Attack1_Margin', c_uint16),
        ('Attack1_Rate', c_uint8),
        ('Attack1_ActionID', c_uint8),
        ('Attack1_DelayMin', c_uint8),
        ('Attack1_DelayMax', c_uint8),
        ('Attack1_ConeAngle', c_uint8),
        ('reserve10', c_uint8 * 7),
        ('Attack2_Distance', c_uint16),
        ('Attack2_Margin', c_uint16),
        ('Attack2_Rate', c_uint8),
        ('Attack2_ActionID', c_uint8),
        ('Attack2_DelayMin', c_uint8),
        ('Attack2_DelayMax', c_uint8),
        ('Attack2_ConeAngle', c_uint8),
        ('reserve11', c_uint8 * 7),
        ('Attack3_Distance', c_uint16),
        ('Attack3_Margin', c_uint16),
        ('Attack3_Rate', c_uint8),
        ('Attack3_ActionID', c_uint8),
        ('Attack3_DelayMin', c_uint8),
        ('Attack3_DelayMax', c_uint8),
        ('Attack3_ConeAngle', c_uint8),
        ('reserve12', c_uint8 * 7),
        ('Attack4_Distance', c_uint16),
        ('Attack4_Margin', c_uint16),
        ('Attack4_Rate', c_uint8),
        ('Attack4_ActionID', c_uint8),
        ('Attack4_DelayMin', c_uint8),
        ('Attack4_DelayMax', c_uint8),
        ('Attack4_ConeAngle', c_uint8),
        ('reserve13', c_uint8 * 7),
        ('reserve_last', c_uint8 * 32),
    ]


class THROW_INFO_BANK(Structure):
    _fields_ = [
        ('AtkChrId', c_int32),
        ('DefChrId', c_int32),
        ('Dist', c_float),
        ('DiffAngMin', c_float),
        ('DiffAngMax', c_float),
        ('upperYRange', c_float),
        ('lowerYRange', c_float),
        ('diffAngMyToDef', c_float),
        ('throwTypeId', c_int32),
        ('atkAnimId', c_int32),
        ('defAnimId', c_int32),
        ('escHp', c_uint16),
        ('selfEscCycleTime', c_uint16),
        ('sphereCastRadiusRateTop', c_uint16),
        ('sphereCastRadiusRateLow', c_uint16),
        ('PadType', c_uint8),
        ('AtkEnableState', c_uint8),
        ('atkSorbDmyId', c_uint8),
        ('defSorbDmyId', c_uint8),
        ('throwType', c_uint8),
        ('selfEscCycleCnt', c_uint8),
        ('dmyHasChrDirType', c_uint8),
        ('isTurnAtker', c_uint8, 1),
        ('isSkipWepCate', c_uint8, 1),
        ('isSkipSphereCast', c_uint8, 1),
        ('pad0', c_uint8, 5),
        ('pad1', c_uint8 * 4),
    ]


class ENEMY_STANDARD_INFO_BANK(Structure):
    _fields_ = [
        ('EnemyBehaviorID', c_int32),
        ('HP', c_uint16),
        ('AttackPower', c_uint16),
        ('ChrType', c_int32),
        ('HitHeight', c_float),
        ('HitRadius', c_float),
        ('Weight', c_float),
        ('DynamicFriction', c_float),
        ('StaticFriction', c_float),
        ('UpperDefState', c_int32),
        ('ActionDefState', c_int32),
        ('RotY_per_Second', c_float),
        ('reserve0', c_uint8 * 20),
        ('RotY_per_Second_old', c_uint8),
        ('EnableSideStep', c_uint8),
        ('UseRagdollHit', c_uint8),
        ('reserve_last', c_uint8 * 5),
        ('stamina', c_uint16),
        ('staminaRecover', c_uint16),
        ('staminaConsumption', c_uint16),
        ('deffenct_Phys', c_uint16),
        ('reserve_last2', c_uint8 * 48),
    ]


class BEHAVIOR_PARAM_ST(Structure):
    _fields_ = [
        ('variationId', c_int32),
        ('behaviorJudgeId', c_int32),
        ('ezStateBehaviorType_old', c_uint8),
        ('refType', c_uint8),
        ('pad0', c_uint8 * 2),
        ('refId', c_int32),
        ('sfxVariationId', c_int32),
        ('stamina', c_int32),
        ('mp', c_int32),
        ('category', c_uint8),
        ('heroPoint', c_uint8),
        ('pad1', c_uint8 * 2),
    ]


class NPC_PARAM_ST(Structure):
    _fields_ = [
        ('behaviorVariationId', c_int32),
        ('aiThinkId', c_int32),
        ('nameId', c_int32),
        ('turnVellocity', c_float),
        ('hitHeight', c_float),
        ('hitRadius', c_float),
        ('weight', c_uint32),
        ('hitYOffset', c_float),
        ('hp', c_uint32),
        ('mp', c_uint32),
        ('getSoul', c_uint32),
        ('itemLotId_1', c_int32),
        ('itemLotId_2', c_int32),
        ('itemLotId_3', c_int32),
        ('itemLotId_4', c_int32),
        ('itemLotId_5', c_int32),
        ('itemLotId_6', c_int32),
        ('humanityLotId', c_int32),
        ('spEffectID0', c_int32),
        ('spEffectID1', c_int32),
        ('spEffectID2', c_int32),
        ('spEffectID3', c_int32),
        ('spEffectID4', c_int32),
        ('spEffectID5', c_int32),
        ('spEffectID6', c_int32),
        ('spEffectID7', c_int32),
        ('GameClearSpEffectID', c_int32),
        ('physGuardCutRate', c_float),
        ('magGuardCutRate', c_float),
        ('fireGuardCutRate', c_float),
        ('thunGuardCutRate', c_float),
        ('animIdOffset', c_int32),
        ('moveAnimId', c_int32),
        ('spMoveAnimId1', c_int32),
        ('spMoveAnimId2', c_int32),
        ('networkWarpDist', c_float),
        ('dbgBehaviorR1', c_int32),
        ('dbgBehaviorL1', c_int32),
        ('dbgBehaviorR2', c_int32),
        ('dbgBehaviorL2', c_int32),
        ('dbgBehaviorRL', c_int32),
        ('dbgBehaviorRR', c_int32),
        ('dbgBehaviorRD', c_int32),
        ('dbgBehaviorRU', c_int32),
        ('dbgBehaviorLL', c_int32),
        ('dbgBehaviorLR', c_int32),
        ('dbgBehaviorLD', c_int32),
        ('dbgBehaviorLU', c_int32),
        ('animIdOffset2', c_int32),
        ('partsDamageRate1', c_float),
        ('partsDamageRate2', c_float),
        ('partsDamageRate3', c_float),
        ('partsDamageRate4', c_float),
        ('partsDamageRate5', c_float),
        ('partsDamageRate6', c_float),
        ('partsDamageRate7', c_float),
        ('partsDamageRate8', c_float),
        ('weakPartsDamageRate', c_float),
        ('superArmorRecoverCorrection', c_float),
        ('superArmorBrakeKnockbackDist', c_float),
        ('stamina', c_uint16),
        ('staminaRecoverBaseVel', c_uint16),
        ('def_phys', c_uint16),
        ('def_slash', c_int16),
        ('def_blow', c_int16),
        ('def_thrust', c_int16),
        ('def_mag', c_uint16),
        ('def_fire', c_uint16),
        ('def_thunder', c_uint16),
        ('defFlickPower', c_uint16),
        ('resist_poison', c_uint16),
        ('resist_desease', c_uint16),
        ('resist_blood', c_uint16),
        ('resist_curse', c_uint16),
        ('ghostModelId', c_int16),
        ('normalChangeResouceId', c_int16),
        ('guardAngle', c_int16),
        ('slashGuardCutRate', c_int16),
        ('blowGuardCutRate', c_int16),
        ('thrustGuardCutRate', c_int16),
        ('superArmorDurability', c_int16),
        ('normalChangeTexChrId', c_int16),
        ('dropType', c_uint16),
        ('knockbackRate', c_uint8),
        ('knockbackParamId', c_uint8),
        ('fallDamageDump', c_uint8),
        ('staminaGuardDef', c_uint8),
        ('pcAttrB', c_uint8),
        ('pcAttrW', c_uint8),
        ('pcAttrL', c_uint8),
        ('pcAttrR', c_uint8),
        ('areaAttrB', c_uint8),
        ('areaAttrW', c_uint8),
        ('areaAttrL', c_uint8),
        ('areaAttrR', c_uint8),
        ('mpRecoverBaseVel', c_uint8),
        ('flickDamageCutRate', c_uint8),
        ('defaultLodParamId', c_int8),
        ('drawType', c_uint8),
        ('npcType', c_uint8),
        ('teamType', c_uint8),
        ('moveType', c_uint8),
        ('lockDist', c_uint8),
        ('material', c_uint8),
        ('materialSfx', c_uint8),
        ('material_Weak', c_uint8),
        ('materialSfx_Weak', c_uint8),
        ('partsDamageType', c_uint8),
        ('maxUndurationAng', c_uint8),
        ('guardLevel', c_int8),
        ('burnSfxType', c_uint8),
        ('poisonGuardResist', c_int8),
        ('diseaseGuardResist', c_int8),
        ('bloodGuardResist', c_int8),
        ('curseGuardResist', c_int8),
        ('parryAttack', c_uint8),
        ('parryDefence', c_uint8),
        ('sfxSize', c_uint8),
        ('pushOutCamRegionRadius', c_uint8),
        ('hitStopType', c_uint8),
        ('ladderEndChkOffsetTop', c_uint8),
        ('ladderEndChkOffsetLow', c_uint8),
        ('useRagdollCamHit', c_uint8, 1),
        ('disableClothRigidHit', c_uint8, 1),
        ('useRagdoll', c_uint8, 1),
        ('isDemon', c_uint8, 1),
        ('isGhost', c_uint8, 1),
        ('isNoDamageMotion', c_uint8, 1),
        ('isUnduration', c_uint8, 1),
        ('isChangeWanderGhost', c_uint8, 1),
        ('modelDispMask0', c_uint8, 1),
        ('modelDispMask1', c_uint8, 1),
        ('modelDispMask2', c_uint8, 1),
        ('modelDispMask3', c_uint8, 1),
        ('modelDispMask4', c_uint8, 1),
        ('modelDispMask5', c_uint8, 1),
        ('modelDispMask6', c_uint8, 1),
        ('modelDispMask7', c_uint8, 1),
        ('modelDispMask8', c_uint8, 1),
        ('modelDispMask9', c_uint8, 1),
        ('modelDispMask10', c_uint8, 1),
        ('modelDispMask11', c_uint8, 1),
        ('modelDispMask12', c_uint8, 1),
        ('modelDispMask13', c_uint8, 1),
        ('modelDispMask14', c_uint8, 1),
        ('modelDispMask15', c_uint8, 1),
        ('isEnableNeckTurn', c_uint8, 1),
        ('disableRespawn', c_uint8, 1),
        ('isMoveAnimWait', c_uint8, 1),
        ('isCrowd', c_uint8, 1),
        ('isWeakSaint', c_uint8, 1),
        ('isWeakA', c_uint8, 1),
        ('isWeakB', c_uint8, 1),
        ('pad1', c_uint8, 1),
        ('vowType', c_uint8, 3),
        ('disableInitializeDead', c_uint8, 1),
        ('pad3', c_uint8, 4),
        ('pad2', c_uint8 * 6),
    ]


class ATK_PARAM_ST(Structure):
    _fields_ = [
        ('hit0_Radius', c_float),
        ('hit1_Radius', c_float),
        ('hit2_Radius', c_float),
        ('hit3_Radius', c_float),
        ('knockbackDist', c_float),
        ('hitStopTime', c_float),
        ('spEffectId0', c_int32),
        ('spEffectId1', c_int32),
        ('spEffectId2', c_int32),
        ('spEffectId3', c_int32),
        ('spEffectId4', c_int32),
        ('hit0_DmyPoly1', c_int16),
        ('hit1_DmyPoly1', c_int16),
        ('hit2_DmyPoly1', c_int16),
        ('hit3_DmyPoly1', c_int16),
        ('hit0_DmyPoly2', c_int16),
        ('hit1_DmyPoly2', c_int16),
        ('hit2_DmyPoly2', c_int16),
        ('hit3_DmyPoly2', c_int16),
        ('blowingCorrection', c_uint16),
        ('atkPhysCorrection', c_uint16),
        ('atkMagCorrection', c_uint16),
        ('atkFireCorrection', c_uint16),
        ('atkThunCorrection', c_uint16),
        ('atkStamCorrection', c_uint16),
        ('guardAtkRateCorrection', c_uint16),
        ('guardBreakCorrection', c_uint16),
        ('atkThrowEscapeCorrection', c_uint16),
        ('atkSuperArmorCorrection', c_uint16),
        ('atkPhys', c_uint16),
        ('atkMag', c_uint16),
        ('atkFire', c_uint16),
        ('atkThun', c_uint16),
        ('atkStam', c_uint16),
        ('guardAtkRate', c_uint16),
        ('guardBreakRate', c_uint16),
        ('atkSuperArmor', c_uint16),
        ('atkThrowEscape', c_uint16),
        ('atkObj', c_uint16),
        ('guardStaminaCutRate', c_int16),
        ('guardRate', c_int16),
        ('throwTypeId', c_uint16),
        ('hit0_hitType', c_uint8),
        ('hit1_hitType', c_uint8),
        ('hit2_hitType', c_uint8),
        ('hit3_hitType', c_uint8),
        ('hti0_Priority', c_uint8),
        ('hti1_Priority', c_uint8),
        ('hti2_Priority', c_uint8),
        ('hti3_Priority', c_uint8),
        ('dmgLevel', c_uint8),
        ('mapHitType', c_uint8),
        ('guardCutCancelRate', c_int8),
        ('atkAttribute', c_uint8),
        ('spAttribute', c_uint8),
        ('atkType', c_uint8),
        ('atkMaterial', c_uint8),
        ('atkSize', c_uint8),
        ('defMaterial', c_uint8),
        ('defSfxMaterial', c_uint8),
        ('hitSourceType', c_uint8),
        ('throwFlag', c_uint8),
        ('disableGuard', c_uint8, 1),
        ('disableStaminaAttack', c_uint8, 1),
        ('disableHitSpEffect', c_uint8, 1),
        ('IgnoreNotifyMissSwingForAI', c_uint8, 1),
        ('repeatHitSfx', c_uint8, 1),
        ('isArrowAtk', c_uint8, 1),
        ('isGhostAtk', c_uint8, 1),
        ('isDisableNoDamage', c_uint8, 1),
        ('pad', c_uint8 * 1),
    ]


class NPC_THINK_PARAM_ST(Structure):
    _fields_ = [
        ('logicId', c_int32),
        ('battleGoalID', c_int32),
        ('nearDist', c_float),
        ('midDist', c_float),
        ('farDist', c_float),
        ('outDist', c_float),
        ('BackHomeLife_OnHitEneWal', c_float),
        ('goalID_ToCaution', c_int32),
        ('idAttackCannotMove', c_int32),
        ('goalID_ToFind', c_int32),
        ('callHelp_ActionAnimId', c_int32),
        ('callHelp_CallActionId', c_int32),
        ('eye_dist', c_uint16),
        ('ear_dist', c_uint16),
        ('ear_soundcut_dist', c_uint16),
        ('nose_dist', c_uint16),
        ('maxBackhomeDist', c_uint16),
        ('backhomeDist', c_uint16),
        ('backhomeBattleDist', c_uint16),
        ('nonBattleActLife', c_uint16),
        ('BackHome_LookTargetTime', c_uint16),
        ('BackHome_LookTargetDist', c_uint16),
        ('SightTargetForgetTime', c_uint16),
        ('SoundTargetForgetTime', c_uint16),
        ('BattleStartDist', c_uint16),
        ('callHelp_MyPeerId', c_uint16),
        ('callHelp_CallPeerId', c_uint16),
        ('targetSys_DmgEffectRate', c_uint16),
        ('TeamAttackEffectivity', c_uint8),
        ('eye_angX', c_uint8),
        ('eye_angY', c_uint8),
        ('ear_angX', c_uint8),
        ('ear_angY', c_uint8),
        ('callHelp_CallValidMinDistTarget', c_uint8),
        ('callHelp_CallValidRange', c_uint8),
        ('callHelp_ForgetTimeByArrival', c_uint8),
        ('callHelp_MinWaitTime', c_uint8),
        ('callHelp_MaxWaitTime', c_uint8),
        ('goalAction_ToCaution', c_uint8),
        ('goalAction_ToFind', c_uint8),
        ('callHelp_ReplyBehaviorType', c_uint8),
        ('disablePathMove', c_uint8),
        ('skipArrivalVisibleCheck', c_uint8),
        ('thinkAttr_doAdmirer', c_uint8),
        ('enableNaviFlg_Edge', c_uint8, 1),
        ('enableNaviFlg_LargeSpace', c_uint8, 1),
        ('enableNaviFlg_Ladder', c_uint8, 1),
        ('enableNaviFlg_Hole', c_uint8, 1),
        ('enableNaviFlg_Door', c_uint8, 1),
        ('enableNaviFlg_InSideWall', c_uint8, 1),
        ('enableNaviFlg_reserve0', c_uint8, 2),
        ('enableNaviFlg_reserve1', c_uint8 * 3),
        ('pad0', c_uint8 * 12),
    ]


class MAGIC_PARAM_ST(Structure):
    _fields_ = [
        ('yesNoDialogMessageId', c_int32),
        ('limitCancelSpEffectId', c_int32),
        ('sortId', c_int16),
        ('refId', c_int16),
        ('mp', c_int16),
        ('stamina', c_int16),
        ('iconId', c_int16),
        ('behaviorId', c_int16),
        ('mtrlItemId', c_int16),
        ('replaceMagicId', c_int16),
        ('maxQuantity', c_int16),
        ('heroPoint', c_uint8),
        ('overDexterity', c_uint8),
        ('sfxVariationId', c_int8),
        ('slotLength', c_uint8),
        ('requirementIntellect', c_uint8),
        ('requirementFaith', c_uint8),
        ('analogDexiterityMin', c_uint8),
        ('analogDexiterityMax', c_uint8),
        ('ezStateBehaviorType', c_uint8),
        ('refCategory', c_uint8),
        ('spEffectCategory', c_uint8),
        ('refType', c_uint8),
        ('opmeMenuType', c_uint8),
        ('hasSpEffectType', c_uint8),
        ('replaceCategory', c_uint8),
        ('useLimitCategory', c_uint8),
        ('vowType0', c_uint8, 1),
        ('vowType1', c_uint8, 1),
        ('vowType2', c_uint8, 1),
        ('vowType3', c_uint8, 1),
        ('vowType4', c_uint8, 1),
        ('vowType5', c_uint8, 1),
        ('vowType6', c_uint8, 1),
        ('vowType7', c_uint8, 1),
        ('enable_multi', c_uint8, 1),
        ('enable_multi_only', c_uint8, 1),
        ('isEnchant', c_uint8, 1),
        ('isShieldEnchant', c_uint8, 1),
        ('enable_live', c_uint8, 1),
        ('enable_gray', c_uint8, 1),
        ('enable_white', c_uint8, 1),
        ('enable_black', c_uint8, 1),
        ('disableOffline', c_uint8, 1),
        ('castResonanceMagic', c_uint8, 1),
        ('pad_1', c_uint8, 6),
        ('vowType8', c_uint8, 1),
        ('vowType9', c_uint8, 1),
        ('vowType10', c_uint8, 1),
        ('vowType11', c_uint8, 1),
        ('vowType12', c_uint8, 1),
        ('vowType13', c_uint8, 1),
        ('vowType14', c_uint8, 1),
        ('vowType15', c_uint8, 1),
        ('pad', c_uint8 * 2),
    ]


class MOVE_PARAM_ST(Structure):
    _fields_ = [
        ('stayId', c_int32),
        ('walkF', c_int32),
        ('walkB', c_int32),
        ('walkL', c_int32),
        ('walkR', c_int32),
        ('dashF', c_int32),
        ('dashB', c_int32),
        ('dashL', c_int32),
        ('dashR', c_int32),
        ('superDash', c_int32),
        ('escapeF', c_int32),
        ('escapeB', c_int32),
        ('escapeL', c_int32),
        ('escapeR', c_int32),
        ('turnL', c_int32),
        ('trunR', c_int32),
        ('largeTurnL', c_int32),
        ('largeTurnR', c_int32),
        ('stepMove', c_int32),
        ('flyStay', c_int32),
        ('flyWalkF', c_int32),
        ('flyWalkFL', c_int32),
        ('flyWalkFR', c_int32),
        ('flyWalkFL2', c_int32),
        ('flyWalkFR2', c_int32),
        ('flyDashF', c_int32),
        ('flyDashFL', c_int32),
        ('flyDashFR', c_int32),
        ('flyDashFL2', c_int32),
        ('flyDashFR2', c_int32),
        ('dashEscapeF', c_int32),
        ('dashEscapeB', c_int32),
        ('dashEscapeL', c_int32),
        ('dashEscapeR', c_int32),
        ('analogMoveParamId', c_int32),
        ('pad', c_uint8 * 4),
    ]


class OBJECT_PARAM_ST(Structure):
    _fields_ = [
        ('hp', c_int16),
        ('defense', c_uint16),
        ('extRefTexId', c_int16),
        ('materialId', c_int16),
        ('animBreakIdMax', c_uint8),
        ('isCamHit', c_uint8, 1),
        ('isBreakByPlayerCollide', c_uint8, 1),
        ('isAnimBreak', c_uint8, 1),
        ('isPenetrationBulletHit', c_uint8, 1),
        ('isChrHit', c_uint8, 1),
        ('isAttackBacklash', c_uint8, 1),
        ('isDisableBreakForFirstAppear', c_uint8, 1),
        ('isLadder', c_uint8, 1),
        ('isAnimPauseOnRemoPlay', c_uint8, 1),
        ('isDamageNoHit', c_uint8, 1),
        ('isMoveObj', c_uint8, 1),
        ('pad_1', c_uint8, 5),
        ('defaultLodParamId', c_int8),
        ('breakSfxId', c_int32),
    ]


class BULLET_PARAM_ST(Structure):
    _fields_ = [
        ('atkId_Bullet', c_int32),
        ('sfxId_Bullet', c_int32),
        ('sfxId_Hit', c_int32),
        ('sfxId_Flick', c_int32),
        ('life', c_float),
        ('dist', c_float),
        ('shootInterval', c_float),
        ('gravityInRange', c_float),
        ('gravityOutRange', c_float),
        ('hormingStopRange', c_float),
        ('initVellocity', c_float),
        ('accelInRange', c_float),
        ('accelOutRange', c_float),
        ('maxVellocity', c_float),
        ('minVellocity', c_float),
        ('accelTime', c_float),
        ('homingBeginDist', c_float),
        ('hitRadius', c_float),
        ('hitRadiusMax', c_float),
        ('spreadTime', c_float),
        ('expDelay', c_float),
        ('hormingOffsetRange', c_float),
        ('dmgHitRecordLifeTime', c_float),
        ('externalForce', c_float),
        ('spEffectIDForShooter', c_int32),
        ('autoSearchNPCThinkID', c_int32),
        ('HitBulletID', c_int32),
        ('spEffectId0', c_int32),
        ('spEffectId1', c_int32),
        ('spEffectId2', c_int32),
        ('spEffectId3', c_int32),
        ('spEffectId4', c_int32),
        ('numShoot', c_uint16),
        ('homingAngle', c_int16),
        ('shootAngle', c_int16),
        ('shootAngleInterval', c_int16),
        ('shootAngleXInterval', c_int16),
        ('damageDamp', c_int8),
        ('spelDamageDamp', c_int8),
        ('fireDamageDamp', c_int8),
        ('thunderDamageDamp', c_int8),
        ('staminaDamp', c_int8),
        ('knockbackDamp', c_int8),
        ('shootAngleXZ', c_int8),
        ('lockShootLimitAng', c_uint8),
        ('isPenetrate', c_uint8),
        ('prevVelocityDirRate', c_uint8),
        ('atkAttribute', c_uint8),
        ('spAttribute', c_uint8),
        ('Material_AttackType', c_uint8),
        ('Material_AttackMaterial', c_uint8),
        ('Material_Size', c_uint8),
        ('launchConditionType', c_uint8),
        ('FollowType', c_uint8, 3),
        ('EmittePosType', c_uint8, 3),
        ('isAttackSFX', c_uint8, 1),
        ('isEndlessHit', c_uint8, 1),
        ('isPenetrateMap', c_uint8, 1),
        ('isHitBothTeam', c_uint8, 1),
        ('isUseSharedHitList', c_uint8, 1),
        ('isUseMultiDmyPolyIfPlace', c_uint8, 1),
        ('attachEffectType', c_uint8, 2),
        ('isHitForceMagic', c_uint8, 1),
        ('isIgnoreSfxIfHitWater', c_uint8, 1),
        ('isIgnoreMoveStateIfHitWater', c_uint8, 1),
        ('isHitDarkForceMagic', c_uint8, 1),
        ('pad', c_uint8 * 3),
    ]


class SP_EFFECT_PARAM_ST(Structure):
    _fields_ = [
        ('iconId', c_int32),
        ('conditionHp', c_float),
        ('effectEndurance', c_float),
        ('motionInterval', c_float),
        ('maxHpRate', c_float),
        ('maxMpRate', c_float),
        ('maxStaminaRate', c_float),
        ('slashDamageCutRate', c_float),
        ('blowDamageCutRate', c_float),
        ('thrustDamageCutRate', c_float),
        ('neutralDamageCutRate', c_float),
        ('magicDamageCutRate', c_float),
        ('fireDamageCutRate', c_float),
        ('thunderDamageCutRate', c_float),
        ('physicsAttackRate', c_float),
        ('magicAttackRate', c_float),
        ('fireAttackRate', c_float),
        ('thunderAttackRate', c_float),
        ('physicsAttackPowerRate', c_float),
        ('magicAttackPowerRate', c_float),
        ('fireAttackPowerRate', c_float),
        ('thunderAttackPowerRate', c_float),
        ('physicsAttackPower', c_int32),
        ('magicAttackPower', c_int32),
        ('fireAttackPower', c_int32),
        ('thunderAttackPower', c_int32),
        ('physicsDiffenceRate', c_float),
        ('magicDiffenceRate', c_float),
        ('fireDiffenceRate', c_float),
        ('thunderDiffenceRate', c_float),
        ('physicsDiffence', c_int32),
        ('magicDiffence', c_int32),
        ('fireDiffence', c_int32),
        ('thunderDiffence', c_int32),
        ('NoGuardDamageRate', c_float),
        ('vitalSpotChangeRate', c_float),
        ('normalSpotChangeRate', c_float),
        ('maxHpChangeRate', c_float),
        ('behaviorId', c_int32),
        ('changeHpRate', c_float),
        ('changeHpPoint', c_int32),
        ('changeMpRate', c_float),
        ('changeMpPoint', c_int32),
        ('mpRecoverChangeSpeed', c_int32),
        ('changeStaminaRate', c_float),
        ('changeStaminaPoint', c_int32),
        ('staminaRecoverChangeSpeed', c_int32),
        ('magicEffectTimeChange', c_float),
        ('insideDurability', c_int32),
        ('maxDurability', c_int32),
        ('staminaAttackRate', c_float),
        ('poizonAttackPower', c_int32),
        ('registIllness', c_int32),
        ('registBlood', c_int32),
        ('registCurse', c_int32),
        ('fallDamageRate', c_float),
        ('soulRate', c_float),
        ('equipWeightChangeRate', c_float),
        ('allItemWeightChangeRate', c_float),
        ('soul', c_int32),
        ('animIdOffset', c_int32),
        ('haveSoulRate', c_float),
        ('targetPriority', c_float),
        ('sightSearchEnemyCut', c_int32),
        ('hearingSearchEnemyCut', c_int32),
        ('grabityRate', c_float),
        ('registPoizonChangeRate', c_float),
        ('registIllnessChangeRate', c_float),
        ('registBloodChangeRate', c_float),
        ('registCurseChangeRate', c_float),
        ('soulStealRate', c_float),
        ('lifeReductionRate', c_float),
        ('hpRecoverRate', c_float),
        ('replaceSpEffectId', c_int32),
        ('cycleOccurrenceSpEffectId', c_int32),
        ('atkOccurrenceSpEffectId', c_int32),
        ('guardDefFlickPowerRate', c_float),
        ('guardStaminaCutRate', c_float),
        ('rayCastPassedTime', c_int16),
        ('changeSuperArmorPoint', c_int16),
        ('bowDistRate', c_int16),
        ('spCategory', c_uint16),
        ('categoryPriority', c_uint8),
        ('saveCategory', c_int8),
        ('changeMagicSlot', c_uint8),
        ('changeMiracleSlot', c_uint8),
        ('heroPointDamage', c_int8),
        ('defFlickPower', c_uint8),
        ('flickDamageCutRate', c_uint8),
        ('bloodDamageRate', c_uint8),
        ('dmgLv_None', c_int8),
        ('dmgLv_S', c_int8),
        ('dmgLv_M', c_int8),
        ('dmgLv_L', c_int8),
        ('dmgLv_BlowM', c_int8),
        ('dmgLv_Push', c_int8),
        ('dmgLv_Strike', c_int8),
        ('dmgLv_BlowS', c_int8),
        ('dmgLv_Min', c_int8),
        ('dmgLv_Uppercut', c_int8),
        ('dmgLv_BlowLL', c_int8),
        ('dmgLv_Breath', c_int8),
        ('atkAttribute', c_uint8),
        ('spAttribute', c_uint8),
        ('stateInfo', c_uint8),
        ('wepParamChange', c_uint8),
        ('moveType', c_uint8),
        ('lifeReductionType', c_uint8),
        ('throwCondition', c_uint8),
        ('addBehaviorJudgeId_condition', c_int8),
        ('addBehaviorJudgeId_add', c_uint8),
        ('effectTargetSelf', c_uint8, 1),
        ('effectTargetFriend', c_uint8, 1),
        ('effectTargetEnemy', c_uint8, 1),
        ('effectTargetPlayer', c_uint8, 1),
        ('effectTargetAI', c_uint8, 1),
        ('effectTargetLive', c_uint8, 1),
        ('effectTargetGhost', c_uint8, 1),
        ('effectTargetWhiteGhost', c_uint8, 1),
        ('effectTargetBlackGhost', c_uint8, 1),
        ('effectTargetAttacker', c_uint8, 1),
        ('dispIconNonactive', c_uint8, 1),
        ('useSpEffectEffect', c_uint8, 1),
        ('bAdjustMagicAblity', c_uint8, 1),
        ('bAdjustFaithAblity', c_uint8, 1),
        ('bGameClearBonus', c_uint8, 1),
        ('magParamChange', c_uint8, 1),
        ('miracleParamChange', c_uint8, 1),
        ('clearSoul', c_uint8, 1),
        ('requestSOS', c_uint8, 1),
        ('requestBlackSOS', c_uint8, 1),
        ('requestForceJoinBlackSOS', c_uint8, 1),
        ('requestKickSession', c_uint8, 1),
        ('requestLeaveSession', c_uint8, 1),
        ('requestNpcInveda', c_uint8, 1),
        ('noDead', c_uint8, 1),
        ('bCurrHPIndependeMaxHP', c_uint8, 1),
        ('corrosionIgnore', c_uint8, 1),
        ('sightSearchCutIgnore', c_uint8, 1),
        ('hearingSearchCutIgnore', c_uint8, 1),
        ('antiMagicIgnore', c_uint8, 1),
        ('fakeTargetIgnore', c_uint8, 1),
        ('fakeTargetIgnoreUndead', c_uint8, 1),
        ('fakeTargetIgnoreAnimal', c_uint8, 1),
        ('grabityIgnore', c_uint8, 1),
        ('disablePoison', c_uint8, 1),
        ('disableDisease', c_uint8, 1),
        ('disableBlood', c_uint8, 1),
        ('disableCurse', c_uint8, 1),
        ('enableCharm', c_uint8, 1),
        ('enableLifeTime', c_uint8, 1),
        ('hasTarget', c_uint8, 1),
        ('isFireDamageCancel', c_uint8, 1),
        ('isExtendSpEffectLife', c_uint8, 1),
        ('requestLeaveColiseumSession', c_uint8, 1),
        ('pad_2', c_uint8, 4),
        ('vowType0', c_uint8, 1),
        ('vowType1', c_uint8, 1),
        ('vowType2', c_uint8, 1),
        ('vowType3', c_uint8, 1),
        ('vowType4', c_uint8, 1),
        ('vowType5', c_uint8, 1),
        ('vowType6', c_uint8, 1),
        ('vowType7', c_uint8, 1),
        ('vowType8', c_uint8, 1),
        ('vowType9', c_uint8, 1),
        ('vowType10', c_uint8, 1),
        ('vowType11', c_uint8, 1),
        ('vowType12', c_uint8, 1),
        ('vowType13', c_uint8, 1),
        ('vowType14', c_uint8, 1),
        ('vowType15', c_uint8, 1),
        ('pad1', c_uint8 * 11),
    ]


class SP_EFFECT_VFX_PARAM_ST(Structure):
    _fields_ = [
        ('midstSfxId', c_int32),
        ('midstSeId', c_int32),
        ('initSfxId', c_int32),
        ('initSeId', c_int32),
        ('finishSfxId', c_int32),
        ('finishSeId', c_int32),
        ('camouflageBeginDist', c_float),
        ('camouflageEndDist', c_float),
        ('transformProtectorId', c_int32),
        ('midstDmyId', c_int16),
        ('initDmyId', c_int16),
        ('finishDmyId', c_int16),
        ('effectType', c_uint8),
        ('soulParamIdForWepEnchant', c_uint8),
        ('playCategory', c_uint8),
        ('playPriority', c_uint8),
        ('existEffectForLarge', c_uint8, 1),
        ('existEffectForSoul', c_uint8, 1),
        ('effectInvisibleAtCamouflage', c_uint8, 1),
        ('useCamouflage', c_uint8, 1),
        ('invisibleAtFriendCamouflage', c_uint8, 1),
        ('addMapAreaBlockOffset', c_uint8, 1),
        ('halfCamouflage', c_uint8, 1),
        ('isFullBodyTransformProtectorId', c_uint8, 1),
        ('isInvisibleWeapon', c_uint8, 1),
        ('isSilence', c_uint8, 1),
        ('pad_1', c_uint8, 6),
        ('pad', c_uint8 * 16),
    ]


class TALK_PARAM_ST(Structure):
    _fields_ = [
        ('msgId', c_int32),
        ('voiceId', c_int32),
        ('motionId', c_int32),
        ('returnPos', c_int32),
        ('reactionId', c_int32),
        ('eventId', c_int32),
        ('isMotionLoop', c_uint8),
        ('pad0', c_uint8 * 7),
    ]


class MENU_PARAM_COLOR_TABLE_ST(Structure):
    _fields_ = [
        ('r', c_uint8),
        ('g', c_uint8),
        ('b', c_uint8),
        ('a', c_uint8),
    ]


class ITEMLOT_PARAM_ST(Structure):
    _fields_ = [
        ('lotItemId01', c_int32),
        ('lotItemId02', c_int32),
        ('lotItemId03', c_int32),
        ('lotItemId04', c_int32),
        ('lotItemId05', c_int32),
        ('lotItemId06', c_int32),
        ('lotItemId07', c_int32),
        ('lotItemId08', c_int32),
        ('lotItemCategory01', c_int32),
        ('lotItemCategory02', c_int32),
        ('lotItemCategory03', c_int32),
        ('lotItemCategory04', c_int32),
        ('lotItemCategory05', c_int32),
        ('lotItemCategory06', c_int32),
        ('lotItemCategory07', c_int32),
        ('lotItemCategory08', c_int32),
        ('lotItemBasePoint01', c_uint16),
        ('lotItemBasePoint02', c_uint16),
        ('lotItemBasePoint03', c_uint16),
        ('lotItemBasePoint04', c_uint16),
        ('lotItemBasePoint05', c_uint16),
        ('lotItemBasePoint06', c_uint16),
        ('lotItemBasePoint07', c_uint16),
        ('lotItemBasePoint08', c_uint16),
        ('cumulateLotPoint01', c_uint16),
        ('cumulateLotPoint02', c_uint16),
        ('cumulateLotPoint03', c_uint16),
        ('cumulateLotPoint04', c_uint16),
        ('cumulateLotPoint05', c_uint16),
        ('cumulateLotPoint06', c_uint16),
        ('cumulateLotPoint07', c_uint16),
        ('cumulateLotPoint08', c_uint16),
        ('getItemFlagId01', c_int32),
        ('getItemFlagId02', c_int32),
        ('getItemFlagId03', c_int32),
        ('getItemFlagId04', c_int32),
        ('getItemFlagId05', c_int32),
        ('getItemFlagId06', c_int32),
        ('getItemFlagId07', c_int32),
        ('getItemFlagId08', c_int32),
        ('getItemFlagId', c_int32),
        ('cumulateNumFlagId', c_int32),
        ('cumulateNumMax', c_uint8),
        ('lotItem_Rarity', c_uint8),
        ('lotItemNum01', c_uint8),
        ('lotItemNum02', c_uint8),
        ('lotItemNum03', c_uint8),
        ('lotItemNum04', c_uint8),
        ('lotItemNum05', c_uint8),
        ('lotItemNum06', c_uint8),
        ('lotItemNum07', c_uint8),
        ('lotItemNum08', c_uint8),
        ('enableLuck01', c_uint16, 1),
        ('enableLuck02', c_uint16, 1),
        ('enableLuck03', c_uint16, 1),
        ('enableLuck04', c_uint16, 1),
        ('enableLuck05', c_uint16, 1),
        ('enableLuck06', c_uint16, 1),
        ('enableLuck07', c_uint16, 1),
        ('enableLuck08', c_uint16, 1),
        ('cumulateReset01', c_uint16, 1),
        ('cumulateReset02', c_uint16, 1),
        ('cumulateReset03', c_uint16, 1),
        ('cumulateReset04', c_uint16, 1),
        ('cumulateReset05', c_uint16, 1),
        ('cumulateReset06', c_uint16, 1),
        ('cumulateReset07', c_uint16, 1),
        ('cumulateReset08', c_uint16, 1),
    ]


class CHARACTER_INIT_PARAM(Structure):
    _fields_ = [
        ('baseRec_mp', c_float),
        ('baseRec_sp', c_float),
        ('red_Falldam', c_float),
        ('soul', c_int32),
        ('equip_Wep_Right', c_int32),
        ('equip_Subwep_Right', c_int32),
        ('equip_Wep_Left', c_int32),
        ('equip_Subwep_Left', c_int32),
        ('equip_Helm', c_int32),
        ('equip_Armer', c_int32),
        ('equip_Gaunt', c_int32),
        ('equip_Leg', c_int32),
        ('equip_Arrow', c_int32),
        ('equip_Bolt', c_int32),
        ('equip_SubArrow', c_int32),
        ('equip_SubBolt', c_int32),
        ('equip_Accessory01', c_int32),
        ('equip_Accessory02', c_int32),
        ('equip_Accessory03', c_int32),
        ('equip_Accessory04', c_int32),
        ('equip_Accessory05', c_int32),
        ('equip_Skill_01', c_int32),
        ('equip_Skill_02', c_int32),
        ('equip_Skill_03', c_int32),
        ('equip_Spell_01', c_int32),
        ('equip_Spell_02', c_int32),
        ('equip_Spell_03', c_int32),
        ('equip_Spell_04', c_int32),
        ('equip_Spell_05', c_int32),
        ('equip_Spell_06', c_int32),
        ('equip_Spell_07', c_int32),
        ('item_01', c_int32),
        ('item_02', c_int32),
        ('item_03', c_int32),
        ('item_04', c_int32),
        ('item_05', c_int32),
        ('item_06', c_int32),
        ('item_07', c_int32),
        ('item_08', c_int32),
        ('item_09', c_int32),
        ('item_10', c_int32),
        ('npcPlayerFaceGenId', c_int32),
        ('npcPlayerThinkId', c_int32),
        ('baseHp', c_uint16),
        ('baseMp', c_uint16),
        ('baseSp', c_uint16),
        ('arrowNum', c_uint16),
        ('boltNum', c_uint16),
        ('subArrowNum', c_uint16),
        ('subBoltNum', c_uint16),
        ('QWC_sb', c_int16),
        ('QWC_mw', c_int16),
        ('QWC_cd', c_int16),
        ('soulLv', c_int16),
        ('baseVit', c_uint8),
        ('baseWil', c_uint8),
        ('baseEnd', c_uint8),
        ('baseStr', c_uint8),
        ('baseDex', c_uint8),
        ('baseMag', c_uint8),
        ('baseFai', c_uint8),
        ('baseLuc', c_uint8),
        ('baseHeroPoint', c_uint8),
        ('baseDurability', c_uint8),
        ('itemNum_01', c_uint8),
        ('itemNum_02', c_uint8),
        ('itemNum_03', c_uint8),
        ('itemNum_04', c_uint8),
        ('itemNum_05', c_uint8),
        ('itemNum_06', c_uint8),
        ('itemNum_07', c_uint8),
        ('itemNum_08', c_uint8),
        ('itemNum_09', c_uint8),
        ('itemNum_10', c_uint8),
        ('bodyScaleHead', c_int8),
        ('bodyScaleBreast', c_int8),
        ('bodyScaleAbdomen', c_int8),
        ('bodyScaleArm', c_int8),
        ('bodyScaleLeg', c_int8),
        ('gestureId0', c_int8),
        ('gestureId1', c_int8),
        ('gestureId2', c_int8),
        ('gestureId3', c_int8),
        ('gestureId4', c_int8),
        ('gestureId5', c_int8),
        ('gestureId6', c_int8),
        ('npcPlayerType', c_uint8),
        ('npcPlayerDrawType', c_uint8),
        ('npcPlayerSex', c_uint8),
        ('vowType', c_uint8, 4),
        ('pad', c_uint8, 4),
        ('pad0', c_uint8 * 10),
    ]


class FACE_PARAM_ST(Structure):
    _fields_ = [
        ('faceGeoData00', c_uint8),
        ('faceGeoData01', c_uint8),
        ('faceGeoData02', c_uint8),
        ('faceGeoData03', c_uint8),
        ('faceGeoData04', c_uint8),
        ('faceGeoData05', c_uint8),
        ('faceGeoData06', c_uint8),
        ('faceGeoData07', c_uint8),
        ('faceGeoData08', c_uint8),
        ('faceGeoData09', c_uint8),
        ('faceGeoData10', c_uint8),
        ('faceGeoData11', c_uint8),
        ('faceGeoData12', c_uint8),
        ('faceGeoData13', c_uint8),
        ('faceGeoData14', c_uint8),
        ('faceGeoData15', c_uint8),
        ('faceGeoData16', c_uint8),
        ('faceGeoData17', c_uint8),
        ('faceGeoData18', c_uint8),
        ('faceGeoData19', c_uint8),
        ('faceGeoData20', c_uint8),
        ('faceGeoData21', c_uint8),
        ('faceGeoData22', c_uint8),
        ('faceGeoData23', c_uint8),
        ('faceGeoData24', c_uint8),
        ('faceGeoData25', c_uint8),
        ('faceGeoData26', c_uint8),
        ('faceGeoData27', c_uint8),
        ('faceGeoData28', c_uint8),
        ('faceGeoData29', c_uint8),
        ('faceGeoData30', c_uint8),
        ('faceGeoData31', c_uint8),
        ('faceGeoData32', c_uint8),
        ('faceGeoData33', c_uint8),
        ('faceGeoData34', c_uint8),
        ('faceGeoData35', c_uint8),
        ('faceGeoData36', c_uint8),
        ('faceGeoData37', c_uint8),
        ('faceGeoData38', c_uint8),
        ('faceGeoData39', c_uint8),
        ('faceGeoData40', c_uint8),
        ('faceGeoData41', c_uint8),
        ('faceGeoData42', c_uint8),
        ('faceGeoData43', c_uint8),
        ('faceGeoData44', c_uint8),
        ('faceGeoData45', c_uint8),
        ('faceGeoData46', c_uint8),
        ('faceGeoData47', c_uint8),
        ('faceGeoData48', c_uint8),
        ('faceGeoData49', c_uint8),
        ('faceTexData00', c_uint8),
        ('faceTexData01', c_uint8),
        ('faceTexData02', c_uint8),
        ('faceTexData03', c_uint8),
        ('faceTexData04', c_uint8),
        ('faceTexData05', c_uint8),
        ('faceTexData06', c_uint8),
        ('faceTexData07', c_uint8),
        ('faceTexData08', c_uint8),
        ('faceTexData09', c_uint8),
        ('faceTexData10', c_uint8),
        ('faceTexData11', c_uint8),
        ('faceTexData12', c_uint8),
        ('faceTexData13', c_uint8),
        ('faceTexData14', c_uint8),
        ('faceTexData15', c_uint8),
        ('faceTexData16', c_uint8),
        ('faceTexData17', c_uint8),
        ('faceTexData18', c_uint8),
        ('faceTexData19', c_uint8),
        ('faceTexData20', c_uint8),
        ('faceTexData21', c_uint8),
        ('faceTexData22', c_uint8),
        ('faceTexData23', c_uint8),
        ('faceTexData24', c_uint8),
        ('faceTexData25', c_uint8),
        ('faceTexData26', c_uint8),
        ('faceTexData27', c_uint8),
        ('faceTexData28', c_uint8),
        ('faceTexData29', c_uint8),
        ('faceTexData30', c_uint8),
        ('faceTexData31', c_uint8),
        ('faceTexData32', c_uint8),
        ('faceTexData33', c_uint8),
        ('faceTexData34', c_uint8),
        ('faceTexData35', c_uint8),
        ('faceTexData36', c_uint8),
        ('faceTexData37', c_uint8),
        ('faceTexData38', c_uint8),
        ('faceTexData39', c_uint8),
        ('faceTexData40', c_uint8),
        ('faceTexData41', c_uint8),
        ('faceTexData42', c_uint8),
        ('faceTexData43', c_uint8),
        ('faceTexData44', c_uint8),
        ('faceTexData45', c_uint8),
        ('faceTexData46', c_uint8),
        ('faceTexData47', c_uint8),
        ('faceTexData48', c_uint8),
        ('faceTexData49', c_uint8),
        ('hairStyle', c_uint8),
        ('hairColor_Base', c_uint8),
        ('hairColor_R', c_uint8),
        ('hairColor_G', c_uint8),
        ('hairColor_B', c_uint8),
        ('eyeColor_R', c_uint8),
        ('eyeColor_G', c_uint8),
        ('eyeColor_B', c_uint8),
        ('pad', c_uint8 * 20),
    ]


class RAGDOLL_PARAM_ST(Structure):
    _fields_ = [
        ('hierarchyGain', c_float),
        ('velocityDamping', c_float),
        ('accelGain', c_float),
        ('velocityGain', c_float),
        ('positionGain', c_float),
        ('maxLinerVelocity', c_float),
        ('maxAngularVelocity', c_float),
        ('snapGain', c_float),
        ('enable', c_uint8),
        ('partsHitMaskNo', c_int8),
        ('pad', c_uint8 * 14),
    ]


class QWC_CHANGE_PARAM_ST(Structure):
    _fields_ = [
        ('pcAttrB', c_int16),
        ('pcAttrW', c_int16),
        ('pcAttrL', c_int16),
        ('pcAttrR', c_int16),
        ('areaAttrB', c_int16),
        ('areaAttrW', c_int16),
        ('areaAttrL', c_int16),
        ('areaAttrR', c_int16),
    ]


class QWC_JUDGE_PARAM_ST(Structure):
    _fields_ = [
        ('pcJudgeUnderWB', c_int16),
        ('pcJudgeTopWB', c_int16),
        ('pcJudgeUnderLR', c_int16),
        ('pcJudgeTopLR', c_int16),
        ('areaJudgeUnderWB', c_int16),
        ('areaJudgeTopWB', c_int16),
        ('areaJudgeUnderLR', c_int16),
        ('areaJudgeTopLR', c_int16),
    ]


class GAME_AREA_PARAM_ST(Structure):
    _fields_ = [
        ('bonusSoul_single', c_uint32),
        ('bonusSoul_multi', c_uint32),
        ('humanityPointCountFlagIdTop', c_int32),
        ('humanityDropPoint1', c_uint16),
        ('humanityDropPoint2', c_uint16),
        ('humanityDropPoint3', c_uint16),
        ('humanityDropPoint4', c_uint16),
        ('humanityDropPoint5', c_uint16),
        ('humanityDropPoint6', c_uint16),
        ('humanityDropPoint7', c_uint16),
        ('humanityDropPoint8', c_uint16),
        ('humanityDropPoint9', c_uint16),
        ('humanityDropPoint10', c_uint16),
    ]


class SKELETON_PARAM_ST(Structure):
    _fields_ = [
        ('neckTurnGain', c_float),
        ('originalGroundHeightMS', c_int16),
        ('minAnkleHeightMS', c_int16),
        ('maxAnkleHeightMS', c_int16),
        ('cosineMaxKneeAngle', c_int16),
        ('cosineMinKneeAngle', c_int16),
        ('footPlantedAnkleHeightMS', c_int16),
        ('footRaisedAnkleHeightMS', c_int16),
        ('raycastDistanceUp', c_int16),
        ('raycastDistanceDown', c_int16),
        ('footEndLS_X', c_int16),
        ('footEndLS_Y', c_int16),
        ('footEndLS_Z', c_int16),
        ('onOffGain', c_int16),
        ('groundAscendingGain', c_int16),
        ('groundDescendingGain', c_int16),
        ('footRaisedGain', c_int16),
        ('footPlantedGain', c_int16),
        ('footUnlockGain', c_int16),
        ('kneeAxisType', c_uint8),
        ('useFootLocking', c_uint8),
        ('footPlacementOn', c_uint8),
        ('twistKneeAxisType', c_uint8),
        ('neckTurnPriority', c_int8),
        ('neckTurnMaxAngle', c_uint8),
        ('pad1', c_uint8 * 2),
    ]


class CACL_CORRECT_GRAPH_ST(Structure):
    _fields_ = [
        ('stageMaxVal0', c_float),
        ('stageMaxVal1', c_float),
        ('stageMaxVal2', c_float),
        ('stageMaxVal3', c_float),
        ('stageMaxVal4', c_float),
        ('stageMaxGrowVal0', c_float),
        ('stageMaxGrowVal1', c_float),
        ('stageMaxGrowVal2', c_float),
        ('stageMaxGrowVal3', c_float),
        ('stageMaxGrowVal4', c_float),
        ('adjPt_maxGrowVal0', c_float),
        ('adjPt_maxGrowVal1', c_float),
        ('adjPt_maxGrowVal2', c_float),
        ('adjPt_maxGrowVal3', c_float),
        ('adjPt_maxGrowVal4', c_float),
        ('init_inclination_soul', c_float),
        ('adjustment_value', c_float),
        ('boundry_inclination_soul', c_float),
        ('boundry_value', c_float),
        ('pad', c_uint8 * 4),
    ]


class LOCK_CAM_PARAM_ST(Structure):
    _fields_ = [
        ('camDistTarget', c_float),
        ('rotRangeMinX', c_float),
        ('lockRotXShiftRatio', c_float),
        ('chrOrgOffset_Y', c_float),
        ('chrLockRangeMaxRadius', c_float),
        ('camFovY', c_float),
        ('pad', c_uint8 * 8),
    ]


class OBJ_ACT_PARAM_ST(Structure):
    _fields_ = [
        ('actionEnableMsgId', c_int32),
        ('actionFailedMsgId', c_int32),
        ('spQualifiedPassEventFlag', c_int32),
        ('validDist', c_uint16),
        ('playerAnimId', c_uint16),
        ('chrAnimId', c_uint16),
        ('spQualifiedId', c_uint16),
        ('spQualifiedId2', c_uint16),
        ('objDummyId', c_uint8),
        ('objAnimId', c_uint8),
        ('validPlayerAngle', c_uint8),
        ('spQualifiedType', c_uint8),
        ('spQualifiedType2', c_uint8),
        ('validObjAngle', c_uint8),
        ('chrSorbType', c_uint8),
        ('eventKickTiming', c_uint8),
        ('pad1', c_uint8 * 2),
    ]


class HIT_MTRL_PARAM_ST(Structure):
    _fields_ = [
        ('aiVolumeRate', c_float),
        ('spEffectIdOnHit0', c_int32),
        ('spEffectIdOnHit1', c_int32),
        ('footEffectHeightType', c_uint8, 2),
        ('footEffectDirType', c_uint8, 2),
        ('floorHeightType', c_uint8, 2),
        ('pad0', c_uint8 * 3),
    ]


class KNOCKBACK_PARAM_ST(Structure):
    _fields_ = [
        ('damage_Min_ContTime', c_float),
        ('damage_S_ContTime', c_float),
        ('damage_M_ContTime', c_float),
        ('damage_L_ContTime', c_float),
        ('damage_BlowS_ContTime', c_float),
        ('damage_BlowM_ContTime', c_float),
        ('damage_Strike_ContTime', c_float),
        ('damage_Uppercut_ContTime', c_float),
        ('damage_Push_ContTime', c_float),
        ('damage_Breath_ContTime', c_float),
        ('damage_HeadShot_ContTime', c_float),
        ('guard_S_ContTime', c_float),
        ('guard_L_ContTime', c_float),
        ('guard_LL_ContTime', c_float),
        ('guardBrake_ContTime', c_float),
        ('damage_Min_DecTime', c_float),
        ('damage_S_DecTime', c_float),
        ('damage_M_DecTime', c_float),
        ('damage_L_DecTime', c_float),
        ('damage_BlowS_DecTime', c_float),
        ('damage_BlowM_DecTime', c_float),
        ('damage_Strike_DecTime', c_float),
        ('damage_Uppercut_DecTime', c_float),
        ('damage_Push_DecTime', c_float),
        ('damage_Breath_DecTime', c_float),
        ('damage_HeadShot_DecTime', c_float),
        ('guard_S_DecTime', c_float),
        ('guard_L_DecTime', c_float),
        ('guard_LL_DecTime', c_float),
        ('guardBrake_DecTime', c_uint8),
        ('pad', c_float * 8),
    ]


